<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUPLhTxl\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUPLhTxl/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUPLhTxl.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUPLhTxl\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUPLhTxl\App_KernelDevDebugContainer([
    'container.build_hash' => 'UPLhTxl',
    'container.build_id' => '29948a0c',
    'container.build_time' => 1682110569,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUPLhTxl');
