<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZAm6ZgP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZAm6ZgP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZAm6ZgP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZAm6ZgP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZAm6ZgP\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZAm6ZgP',
    'container.build_id' => 'd8044291',
    'container.build_time' => 1682171666,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZAm6ZgP');
