<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIaRx47g\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIaRx47g/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIaRx47g.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIaRx47g\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIaRx47g\App_KernelDevDebugContainer([
    'container.build_hash' => 'IaRx47g',
    'container.build_id' => '4c658f86',
    'container.build_time' => 1682112246,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIaRx47g');
